# Generated by Django 4.2.22 on 2025-06-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomMonthlyRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amountUSD', models.DecimalField(decimal_places=2, max_digits=65)),
                ('companyCNumber', models.CharField(max_length=765)),
                ('companyName', models.CharField(max_length=765)),
                ('companyRegnum', models.CharField(max_length=60)),
                ('customs', models.CharField(max_length=765)),
                ('downloadDate', models.DateTimeField()),
                ('itemId', models.CharField(max_length=30)),
                ('importExportFlag', models.CharField(max_length=3)),
                ('itemName', models.TextField()),
                ('measure', models.CharField(max_length=135)),
                ('month', models.CharField(max_length=6)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=65)),
                ('senderReceiver', models.CharField(max_length=9)),
                ('statYearMonth', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'custom_monthly_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'api_datapoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'api_dataset',
                'managed': False,
            },
        ),
    ]
