# Generated by Django 4.2.22 on 2025-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMonthlyExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountUSD', models.DecimalField(decimal_places=2, max_digits=65)),
                ('companyName', models.CharField(max_length=765)),
                ('companyRegnum', models.CharField(max_length=60)),
                ('customs', models.CharField(max_length=765)),
                ('itemId', models.CharField(max_length=30)),
                ('importExportFlag', models.CharField(max_length=3)),
                ('itemName', models.TextField()),
                ('measure', models.CharField(max_length=135)),
                ('month', models.CharField(max_length=6)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=65)),
                ('senderReceiver', models.CharField(max_length=9)),
                ('year', models.IntegerField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'custom_monthly_export_e',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomMonthlyImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SumOfamountUSD', models.DecimalField(decimal_places=2, max_digits=65)),
                ('itemId', models.CharField(max_length=30)),
                ('itemName', models.TextField()),
                ('measure', models.CharField(max_length=135)),
                ('SumOfquantity', models.DecimalField(decimal_places=2, max_digits=65)),
                ('senderReceiver', models.CharField(max_length=9)),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'custom_monthly_import_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomMonthlyImportSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SumOfamountUSD', models.DecimalField(decimal_places=2, max_digits=65)),
                ('itemId', models.CharField(max_length=30)),
                ('itemName', models.TextField()),
                ('measure', models.CharField(max_length=135)),
                ('SumOfquantity', models.DecimalField(decimal_places=2, max_digits=65)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'custom_monthly_import_summary_all',
                'managed': False,
            },
        ),
    ]
