# Generated by Django 4.2.22 on 2025-06-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_custommonthlyexport_custommonthlyimport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMonthlyImportCustom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('SumOfamountUSD', models.DecimalField(decimal_places=2, max_digits=65)),
                ('itemId', models.CharField(max_length=30)),
                ('itemName', models.TextField()),
                ('measure', models.CharField(max_length=135)),
                ('SumOfquantity', models.DecimalField(decimal_places=2, max_digits=65)),
                ('customs', models.TextField()),
                ('month', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'custom_monthly_import_custom',
                'managed': False,
            },
        ),
    ]
