# Generated by Django 4.2.22 on 2025-06-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_custommonthlyimportcustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('code_2601', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('code_2603', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('code_2701', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('code_2709', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('value_2601', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('value_2603', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('value_2701', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('value_2709', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('avg7_2601', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('avg7_2603', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('avg7_2701', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('avg7_2709', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month_avg_2601', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month_avg_2603', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month_avg_2701', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month_avg_2709', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cumulative_2601', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cumulative_2603', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cumulative_2701', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cumulative_2709', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_2601', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_2603', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_2701', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_2709', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_avg7_2601', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_avg7_2603', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_avg7_2701', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_avg7_2709', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_month_avg_2601', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_month_avg_2603', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_month_avg_2701', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_month_avg_2709', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'export_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExportDailySecondaryDB',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.exportdaily',),
        ),
    ]
