# Generated by Django 4.2.22 on 2025-07-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exportdaily_exportdailysecondarydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_import', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('food_products', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('oil_products', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vehicles', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_import_today', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('food_products_today', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('oil_products_today', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vehicles_today', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('others_today', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('total_import_7d_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('food_products_7d_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('oil_products_7d_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vehicles_7d_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('others_7d_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_import_month_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('food_products_month_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('oil_products_month_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vehicles_month_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('others_month_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'import_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ExportDailySecondaryDB',
        ),
    ]
