# Generated by Django 4.2.22 on 2025-07-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_importdaily_delete_exportdailysecondarydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('official_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('daily_change', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'currency_change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=16, null=True)),
                ('trade_type', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('seller', models.CharField(blank=True, max_length=128, null=True)),
                ('product_name_type', models.CharField(blank=True, max_length=128, null=True)),
                ('quantity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('prev_day_mnt_bank_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('prev_day_usd_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('asking_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('asking_total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('asking_total_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'failed_trades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('a80', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ai92', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ai95', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('diesel_winter', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('diesel_summer', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('diesel', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('avg_a80', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('avg_ai92', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('avg_ai95', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('avg_diesel', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month_avg_a80', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month_avg_ai92', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month_avg_ai95', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month_avg_diesel', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'fuel_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MiningAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=10, null=True)),
                ('trade_type', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name_type', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('price_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prev_day_mnt_bank_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prev_day_usd_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('asking_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deal_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asking_total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deal_total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_amount_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_mnt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra_income_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('coal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('copper', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fluorspar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'trades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SxcoalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('raw_coking_coal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('washed_coking_coal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('usd_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cny_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'sxcoal_price',
                'managed': False,
            },
        ),
    ]
