# Generated by Django 4.2.22 on 2025-07-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_currencymove_failtrade_fuelimport_miningauction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommonthlyraw',
            options={},
        ),
    ]
