# Generated by Django 5.2.8 on 2025-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_custommonthlyraw_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommonthlyexport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='custommonthlyimport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='custommonthlyimportcustom',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='custommonthlyimportsum',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='custommonthlyraw',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exportdaily',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='custommonthlyraw',
            name='customs',
            field=models.CharField(db_index=True, max_length=765),
        ),
        migrations.AlterField(
            model_name='custommonthlyraw',
            name='month',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='custommonthlyraw',
            name='senderReceiver',
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='custommonthlyraw',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='custommonthlyraw',
            index=models.Index(fields=['year', 'month'], name='custom_mont_year_601f15_idx'),
        ),
        migrations.AddIndex(
            model_name='custommonthlyraw',
            index=models.Index(fields=['senderReceiver', 'customs'], name='custom_mont_senderR_60c2ec_idx'),
        ),
    ]
